Tourist data per Location

In [1]:
import pandas as pd

hotel = pd.read_csv('Hotel.csv')
restaurant = pd.read_csv('Restaurant.csv')
tourist = pd.read_csv('Tourist_site.csv')

In [2]:
print (hotel)
print ("---------end------------")
print (restaurant)
print ("---------end------------")
print (tourist)
print ("---------end------------")

                               Name          City          Barangay  \
0   Two Seasons Coron Bayside Hotel         Coron          Tagumpay
1            New World Makati Hotel        Makati         Esperanza
2                  Taal Vista Hotel      Tagaytay         Aguinaldo
3            Tagaytay Wingate Manor      Tagaytay            Maitim
4           Somerset Alabang Manila       Alabang         Filinvest
5           Hotel Kimberly Tagaytay      Tagaytay          Kaybagal
6                     DusitD2 Davao         Davao      Stella Hizon
7               Acacia Hotel Manila       Alabang         Filinvest
8                    Kandaya Resort  Daanbantayan             Agujo
9              THE PENINSULA MANILA        Makati  Ayala cor Makati
10        Bayview Park Hotel Manila        Manila    United Nations
11  Sofitel Philippine Plaza Manila        Manila   Roxas Boulevard
12            Red Planet Manila Bay        Manila        Manila Bay
13            1775 Adriatico Suites        Manila          Brgy 699
14            Hotel Kimberly Manila        Manila            Malate
15               City Garden Suites        Manila            Ermita
16             Regency Grand Suites        Manila       Brich Condo
17                     Heroes Hotel        Manila       Florentiono
18                 The Manila Hotel        Manila        Rizal Park
19            Wanderers Guest House        Manila            Nakpil
20   Crimson Resort and Spa, Mactan          Cebu         Lapu Lapu
21  Jpark Island Resort & Waterpark          Cebu          Maribago
22    Movenpick Hotel Mactan Island          Cebu      Punta Engano
23           Seda Central Bloc Cebu          Cebu           IT Park
24            Lubi Resort Santander          Cebu         Poblacion

           Province                                          Amenities  \
0   Busuanga Island             Fitness Center with Gym / Workout Room
1               NCR             Fitness Center with Gym / Workout Room
2        Calabarzon             Fitness Center with Gym / Workout Room
3        Calabarzon             Fitness Center with Gym / Workout Room
4               NCR             Fitness Center with Gym / Workout Room
5        Calabarzon             Fitness Center with Gym / Workout Room
6          Mindanao  Fitness Center with Gym / Workout RoomBar / lo...
7               NCR  Free breakfast Kids stay free Free shuttle or ...
8              Cebu  Free breakfast Beach Tennis court Children Act...
9               NCR                Banquets & Meetings Business Center
10              NCR  Free breakfast Children Activities Airport tra...
11              NCR  Valet parkingFree High Speed Internet (WiFi) P...
12              NCR  Business Center with Internet Access24-hour se...
13              NCR  Free breakfastChildren's television networksHi...
14              NCR  Books, DVDs, music for childrenAirport transpo...
15              NCR                 MicrowaveRefrigeratorFlatscreen TV
16              NCR             Bicycles availableChildren Activities
17              NCR  Free breakfastEvening entertainmentKids stay free
18              NCR                hotel_amenity_evening_entertainment
19              NCR  hotel_amenity_bar_loungehotel_amenity_beachhot...
20             Cebu  Free breakfastBeachCasino and GamblingKids sta...
21             Cebu           Bar / lounge Beach Evening entertainment
22             Cebu  Bar / lounge BeachEvening entertainmentChildre...
23             Cebu             Fitness Center with Gym / Workout Room
24             Cebu             Fitness Center with Gym / Workout Room

        PriceRange  NumberofRooms  \
0     6100 to 7900             48
1     4800 to 5700            580
2     4194 to 6110            261
3   13333 to 13481             24
4     6991 to 7000            150
5     3200 to 4420             50
6     2744 to 4900            120
7     3987 to 4914            262
8     7904 to 9730             40
9     5514 to 5680            498
10    2275 to 2938            282
11    6492 to 7067            609
12    1800 to 2017            150
13    1678 to 2233             36
14    2082 to 2162             58
15    1786 to 2394            142
16    1710 to 1896             61
17    1360 to 1786             50
18    3871 to 4654            149
19      794 to 833             46
20    4151 to 5170            250
21    4858 to 5659            557
22            5920            245
23            3810            214
24            5438              6

                                            OtherData  \
0   The town has successfully managed to preserve ...
1   El Nido in Palawan is most famous for its para...
2   Tubbataha Reef is regarded as one of the top d...
3   As soon as your flight lands at the airport in...
4   Take a stroll through history lane within the ...
5   Locals and foreign visitors from Manila often ...
6   If you like jumping into or swimming in cool c...
7   Undoubtedly one of the most photographed and i...
8   Many travelers skip Manila and make their way ...
9   The Ifugao people were highly skilled in carvi...
10  Siargao’s rise as a top tourist spot in the Ph...
11  The gateway to the Philippines’ Last Frontier,...
12  Included in the UNESCO World Heritage Natural ...
13  Long hailed as one of the best beaches in the ...
14  It is a trek to get to the hanging coffins in ...
15  A tour of Corregidor Island is a must-see for ...
16  The only thing more exciting than admiring one...
17  If you are unsure where to snorkel to see some...
18  You can take a tour of the former Subic Bay Na...
19  Over the years, the bridge, which was was orig...
20  Mention the best tourist destinations in the P...
21  Danjugan Island is a rainforest-covered island...
22  Have you ever fantasized about having your own...
23  Visitors in Bulusan flock to the Bulusan Volca...
24  Bonbon Beach in Romblon has fine, white sand, ...

                                       CustomerReview
0   "I really like to commend the service provided...
1   Very good service. Food is good also. Siaomai ...
2   Awesome hotel. My family and I were here aroun...
3   Place is a bit far from the highway not to men...
4   It's a priviledge to be able to stay in this g...
5   Everything was flawless. Starting from the boo...
6   Beautiful hotel with excellent customer servic...
7   When I travelled with my friend in the Philipp...
8   We had a wonderful time here. The beachside vi...
9   I waited for almost five months to write this ...
10  My gf stayed here when her flight was cancelle...
11  10/10 Experience in Spiral! They definitely ha...
12  In my 5 years living in the Philippines and mo...
13  Overall stay was so perfect that we actually p...
14  thank you and GOD BLESS,I'm very much apprecia...
15  Stayed for 3 nights because I need to do my ch...
16  Super ganda ng ambiance lalo n pag need mo ng ...
17  This hotel has my preference due to the locati...
18  Been here as our flight was cancelled. Crowded...
19  If you are staying in Manila. Stay here!Its lo...
20  We had a unforgettable experience for celebrat...
21  very nice staff and a good place to catch time...
22  Great experience! Very friendly and accomodati...
23  Most of the time I ask for a room service like...
24  The resort was very hidden, but it also meant ...
---------end------------
                                               Name         City  \
0                                  Cafe Ilang-Ilang       Manila
1                                            Le Bar       Manila
2                                             Li Li       Manila
3                      Yurakuen Japanese Restaurant       Manila
4                                     Summer Palace  Mandaluyong
5                                       Eng Bee Tin       Manila
6                           My Kitchen at the Oasis       Manila
7                     Sky Deck at The Bayleaf Hotel       Manila
8                                       Market Cafe       Manila
9                                        Tim Ho Wan  Mandaluyong
10                    Barbara's Heritage Restaurant       Manila
11                        The Aristocrat Restaurant       Manila
12                                  Bistro Remedios       Manila
13                         Uno Wharf Seafood Palace       Manila
14                           Ristorante Delle Mitre       Manila
15                             Dads-Saisaki-Kamayan       Manila
16                                       Casa Armas       Manila
17                                       Casa Roces        Pasig
18                              Tao Yuan Restaurant       Manila
19                         Korean Palace Restaurant       Manila
20                               Mario's Restaurant       Baguio
21                                           Hamada       Baguio
22                                     Mama's Table       Baguio
23                                     Bistro Lokal       Baguio
24  O Dong Tong Samgyeopsal House Korean Restaurant       Baguio

              Barangay Province                                Specialty  \
0           Rizal Park      NCR                      Vegetarian Friendly
1    Centro Commercial      NCR  Vegetarian Friendly, Gluten Free Option
2               Malate      NCR                           Chinese, Asian
3                Roxas      NCR                                 Japanese
4            Shangrila      NCR                                  Chinese
5              Binondo      NCR                                  Chinese
6                 Paco      NCR                 Italian, Pizza, European
7           Intramuros      NCR      Filipino, Bar, Asian, International
8             brgy 734      NCR            International, Asian, Healthy
9             Megamall      NCR                           Chinese, Asian
10          Intramuros      NCR           Filipino, Asian, International
11               Roxas      NCR                                 Filipino
12              Malate      NCR                          Filipino, Asian
13               Calvo      NCR                  Chinese, Asian, Seafood
14          Intramuros      NCR                          Filipino, Asian
15              Ermita      NCR                   Filipino, Sushi, Asian
16              Nakpil      NCR         European, Spanish, Mediterranean
17          San Miguel      NCR                 Spanish, Filipino, Asian
18              Malate      NCR                  Chinese, Seafood, Asian
19              Malate      NCR                  Korean, Barbecue, Asian
20  Upper Session Road   Baguio                                  Spanish
21        Country Club   Baguio                   Japanese, Sushi, Asian
22            Ambuklao   Baguio                                   Dinner
23           Magsaysay   Baguio                    Filipino, Cafe, Asian
24           Naguillan   Baguio                            Asian, Korean

          PriceRange  SeatingCapacity  \
0        350 to 1488              NaN
1                NaN             60.0
2                NaN            287.0
3    ₱1,000 - ₱2,000              NaN
4                NaN             70.0
5                NaN             25.0
6      ₱479 - ₱2,396            400.0
7                NaN             70.0
8        190 to 1490            270.0
9                NaN            105.0
10        195 to 475            300.0
11       ₱240 - ₱479            200.0
12               NaN              NaN
13        190 to 490            210.0
14        275 to 298            300.0
15        295 to 988              NaN
16     ₱479 - ₱2,875             90.0
17               NaN            100.0
18               NaN            200.0
19       ₱240 - ₱479             60.0
20       310 to 2520            134.0
21               NaN            120.0
22               NaN              NaN
23       ₱30 - ₱2000              NaN
24  ₱7,188 - ₱23,960              NaN

                                            OtherData  \
0   CUISINES Italian, Chinese, Japanese, American,...
1   Takeout, Seating, Parking Available, Validated...
2                                    Vegetarian Foods
3                                       Lunch, Dinner
4                                       Lunch, Dinner
5                                       Lunch, Dinner
6                                       Lunch, Dinner
7                               Dinner, Drinks, Lunch
8   Vegan Options, Vegetarian Friendly, Gluten Fre...
9                               Lunch, Dinner, Brunch
10  Reservations, Private Dining, Seating, Serves ...
11                                      Vegan Options
12                                 Vegetarian options
13                                 Vegetarian options
14                                 Vegetarian options
15                                 Vegetarian options
16                          Dinner, Lunch, Late Night
17  Takeout, Reservations, Seating, Serves Alcohol...
18  Takeout, Reservations, Seating, Serves Alcohol...
19                          Dinner, Lunch, Late Night
20                                Gluten Free Options
21  Takeout, Reservations, Wheelchair Accessible, ...
22               Reservations, Seating, Table Service
23                              Lunch, Dinner, Brunch
24                  Lunch, Dinner, Late Night, Drinks

                                       CustomerReview
0   Been here a couple of times, and this might be...
1   I am sending this comment to recommend Mr. Dev...
2   Had our dinner business meeting here last week...
3   It is a real good japenese restaurant. Make su...
4   I have tried eating here for lunch on a Sunday...
5   This is your go to place for that good ube (Pu...
6   I love their MOSCATO wine brand from Australia...
7   i enjoyed our breakfast here, so cozy and food...
8   I never get tired of dining at Market Cafe whe...
9   If you like to eat various types of asian cuis...
10  We found this hidden gem while wandering in th...
11  The last time I ate there was in Manila. I was...
12  Very good Great value for money the food looke...
13  You have to accept that the foods from each re...
14  The servers should be taught how to be nice or...
15  Food served are all freshly cooked, well prese...
16  Cosy restaurant, very well located, fine wines...
17  I like their desserts, specially the turon. It...
18  We enjoyed the food in this restaurant. Fresh ...
19  Another top Korean restaurant with non meat op...
20  Food is still good here as always but has beco...
21  Food was good and priced very well, its not gr...
22  We ate here for a birthday celebration. The am...
23  One of the best dining experience in Baguio. F...
24  The dynamite kimbap is the best in their menu....
---------end------------
                                 Name               City     Barangay  \
0                     Calle Crisologo              Vigan          NaN
1                        Nacpan Beach            El Nido          NaN
2                      Tubbataha Reef       Cagayancillo          NaN
3                       Mayon Volcano              Albay          NaN
4        Intramuros and Fort Santiago             Manila   Intramuros
5               Taal Volcano and Lake           Tagaytay          NaN
6                       Kawasan Falls             Badian          NaN
7                       Kayangan Lake              Coron          NaN
8                          Rizal Park             Manila       Ermita
9                Banaue Rice Terraces      Nueva Viscaya        Batad
10                            Cloud 9       General Luna          NaN
11  Puerto Princesa Underground River    Puerto Princesa          NaN
12                    Chocolate Hills             Batuan          NaN
13                        White Beach              Aklan          NaN
14                    Hanging Coffins             Sagada  Echo Valley
15                  Corregidor Island  Corregidor Island          NaN
16                    Pagsanjan Falls             Laguna          NaN
17                       Coral Garden              Coron          NaN
18                    Jungle Training              Subic     Freeport
19                     Hanging Bridge         Tagbilaran          NaN
20                      Kayangan Lake              Coron          NaN
21                    Danjugan Island            Cauayan          NaN
22                     Sundang Island            Cavinti          NaN
23                      Bayugin Falls            Bulusan          NaN
24                       Bonbon Beach            Romblon          NaN

             Province           Classification  VisitorsPeryear Entrance Fee  \
0              Ilocos  Old Spanish Style Place         335000.0          NaN
1             Palawan             Beach Resort          36000.0          NaN
2             Palawan             Beach Resort          13475.0          NaN
3             Legaspi                  Volcano        1270000.0          NaN
4                 NCR                   Museum        2000000.0           75
5          Calabarzon                     Lake              NaN          NaN
6                Cebu                    Falls              NaN           45
7             Palawan                     Lake              NaN          300
8                 NCR                     Park        1800000.0           50
9              Ifugao            Rice Terraces              NaN          NaN
10            Siargao                  Surfing              NaN         None
11            Palawan                    River        1200000.0          500
12              Bohol                    Hills        2000000.0           50
13            Boracay             Beach Resort        2000000.0          NaN
14  Mountain Province                      NaN              NaN          300
15             Cavite                   Island              NaN          200
16         Calabarzon                    Falls              NaN          270
17            Palawan                   Garden         156000.0          200
18             Bataan                   Jungle              NaN          NaN
19              Bohol                   Bridge              NaN           80
20            Palawan                     Lake              NaN          300
21  Negros Occidental             Beach Resort              NaN         2950
22             Laguna                     Lake              NaN         3400
23           Sorsogon                    Falls              NaN           15
24            Romblon             Beach Resort              NaN         None

                                            OtherData  \
0   The town has successfully managed to preserve ...
1   El Nido in Palawan is most famous for its para...
2   Tubbataha Reef is regarded as one of the top d...
3   As soon as your flight lands at the airport in...
4   Take a stroll through history lane within the ...
5   Locals and foreign visitors from Manila often ...
6   If you like jumping into or swimming in cool c...
7   Undoubtedly one of the most photographed and i...
8   Many travelers skip Manila and make their way ...
9   The Ifugao people were highly skilled in carvi...
10  Siargao’s rise as a top tourist spot in the Ph...
11  The gateway to the Philippines’ Last Frontier,...
12  Included in the UNESCO World Heritage Natural ...
13  Long hailed as one of the best beaches in the ...
14  It is a trek to get to the hanging coffins in ...
15  A tour of Corregidor Island is a must-see for ...
16  The only thing more exciting than admiring one...
17  If you are unsure where to snorkel to see some...
18  You can take a tour of the former Subic Bay Na...
19  Over the years, the bridge, which was was orig...
20  Mention the best tourist destinations in the P...
21  Danjugan Island is a rainforest-covered island...
22  Have you ever fantasized about having your own...
23  Visitors in Bulusan flock to the Bulusan Volca...

In [6]:
tourism = pd.concat([hotel,restaurant,tourist])
tourism

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,Two Seasons Coron Bayside Hotel,Coron,Tagumpay,Busuanga Island,Fitness Center with Gym / Workout Room,6100 to 7900,48.0,The town has successfully managed to preserve ...,"""I really like to commend the service provided...",NaN,NaN,NaN,NaN,NaN
1,New World Makati Hotel,Makati,Esperanza,NCR,Fitness Center with Gym / Workout Room,4800 to 5700,580.0,El Nido in Palawan is most famous for its para...,Very good service. Food is good also. Siaomai ...,NaN,NaN,NaN,NaN,NaN
2,Taal Vista Hotel,Tagaytay,Aguinaldo,Calabarzon,Fitness Center with Gym / Workout Room,4194 to 6110,261.0,Tubbataha Reef is regarded as one of the top d...,Awesome hotel. My family and I were here aroun...,NaN,NaN,NaN,NaN,NaN
3,Tagaytay Wingate Manor,Tagaytay,Maitim,Calabarzon,Fitness Center with Gym / Workout Room,13333 to 13481,24.0,As soon as your flight lands at the airport in...,Place is a bit far from the highway not to men...,NaN,NaN,NaN,NaN,NaN
4,Somerset Alabang Manila,Alabang,Filinvest,NCR,Fitness Center with Gym / Workout Room,6991 to 7000,150.0,Take a stroll through history lane within the ...,It's a priviledge to be able to stay in this g...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,Kayangan Lake,Coron,NaN,Palawan,NaN,NaN,NaN,Mention the best tourist destinations in the P...,The lake has crystal clear waters where you ca...,NaN,NaN,Lake,NaN,300
21,Danjugan Island,Cauayan,NaN,Negros Occidental,NaN,NaN,NaN,Danjugan Island is a rainforest-covered island...,Danjugan Island is for me one of the best plac...,NaN,NaN,Beach Resort,NaN,2950
22,Sundang Island,Cavinti,NaN,Laguna,NaN,NaN,NaN,Have you ever fantasized about having your own...,"Beautiful home. For me, not a place you wanna ...",NaN,NaN,Lake,NaN,3400
23,Bayugin Falls,Bulusan,NaN,Sorsogon,NaN,NaN,NaN,Visitors in Bulusan flock to the Bulusan Volca...,The waterfall is hard to reach. We had to park...,NaN,NaN,Falls,NaN,15
24,Bonbon Beach,Romblon,NaN,Romblon,NaN,NaN,NaN,"Bonbon Beach in Romblon has fine, white sand, ...","Beach by itself is very nice, but old woman, G...",NaN,NaN,Beach Resort,NaN,None

In [7]:
#List unique values in the Province column
tourism.Province.unique()

array(['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

In [25]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

BusuangaIsland = tourism[tourism.Province == 'Busuanga Island']
print (BusuangaIsland)

                              Name   City  Barangay         Province  \
0  Two Seasons Coron Bayside Hotel  Coron  Tagumpay  Busuanga Island

                                Amenities    PriceRange  NumberofRooms  \
0  Fitness Center with Gym / Workout Room  6100 to 7900           48.0

                                           OtherData  \
0  The town has successfully managed to preserve ...

                                      CustomerReview Specialty  \
0  "I really like to commend the service provided...       NaN

   SeatingCapacity Classification  VisitorsPeryear Entrance Fee
0              NaN            NaN              NaN          NaN

In [15]:
#Let's transfer the data to csv file
import csv

with open('BusuangaIsland.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
BusuangaIsland.to_csv("BusuangaIsland.csv", index = False) #transferring data
BusuangaIsland = pd.read_csv("BusuangaIsland.csv")

BusuangaIsland #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,Two Seasons Coron Bayside Hotel,Coron,Tagumpay,Busuanga Island,Fitness Center with Gym / Workout Room,6100 to 7900,48.0,The town has successfully managed to preserve ...,"""I really like to commend the service provided...",NaN,NaN,NaN,NaN,NaN

In [24]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

NCR = tourism[tourism.Province == 'NCR']
print (NCR)

                               Name         City           Barangay Province  \
1            New World Makati Hotel       Makati          Esperanza      NCR
4           Somerset Alabang Manila      Alabang          Filinvest      NCR
7               Acacia Hotel Manila      Alabang          Filinvest      NCR
9              THE PENINSULA MANILA       Makati   Ayala cor Makati      NCR
10        Bayview Park Hotel Manila       Manila     United Nations      NCR
11  Sofitel Philippine Plaza Manila       Manila    Roxas Boulevard      NCR
12            Red Planet Manila Bay       Manila         Manila Bay      NCR
13            1775 Adriatico Suites       Manila           Brgy 699      NCR
14            Hotel Kimberly Manila       Manila             Malate      NCR
15               City Garden Suites       Manila             Ermita      NCR
16             Regency Grand Suites       Manila        Brich Condo      NCR
17                     Heroes Hotel       Manila        Florentiono      NCR
18                 The Manila Hotel       Manila         Rizal Park      NCR
19            Wanderers Guest House       Manila             Nakpil      NCR
0                  Cafe Ilang-Ilang       Manila         Rizal Park      NCR
1                            Le Bar       Manila  Centro Commercial      NCR
2                             Li Li       Manila             Malate      NCR
3      Yurakuen Japanese Restaurant       Manila              Roxas      NCR
4                     Summer Palace  Mandaluyong          Shangrila      NCR
5                       Eng Bee Tin       Manila            Binondo      NCR
6           My Kitchen at the Oasis       Manila               Paco      NCR
7     Sky Deck at The Bayleaf Hotel       Manila         Intramuros      NCR
8                       Market Cafe       Manila           brgy 734      NCR
9                        Tim Ho Wan  Mandaluyong           Megamall      NCR
10    Barbara's Heritage Restaurant       Manila         Intramuros      NCR
11        The Aristocrat Restaurant       Manila              Roxas      NCR
12                  Bistro Remedios       Manila             Malate      NCR
13         Uno Wharf Seafood Palace       Manila              Calvo      NCR
14           Ristorante Delle Mitre       Manila         Intramuros      NCR
15             Dads-Saisaki-Kamayan       Manila             Ermita      NCR
16                       Casa Armas       Manila             Nakpil      NCR
17                       Casa Roces        Pasig         San Miguel      NCR
18              Tao Yuan Restaurant       Manila             Malate      NCR
19         Korean Palace Restaurant       Manila             Malate      NCR
4      Intramuros and Fort Santiago       Manila         Intramuros      NCR
8                        Rizal Park       Manila             Ermita      NCR

                                            Amenities       PriceRange  \
1              Fitness Center with Gym / Workout Room     4800 to 5700
4              Fitness Center with Gym / Workout Room     6991 to 7000
7   Free breakfast Kids stay free Free shuttle or ...     3987 to 4914
9                 Banquets & Meetings Business Center     5514 to 5680
10  Free breakfast Children Activities Airport tra...     2275 to 2938
11  Valet parkingFree High Speed Internet (WiFi) P...     6492 to 7067
12  Business Center with Internet Access24-hour se...     1800 to 2017
13  Free breakfastChildren's television networksHi...     1678 to 2233
14  Books, DVDs, music for childrenAirport transpo...     2082 to 2162
15                 MicrowaveRefrigeratorFlatscreen TV     1786 to 2394
16             Bicycles availableChildren Activities      1710 to 1896
17  Free breakfastEvening entertainmentKids stay free     1360 to 1786
18                hotel_amenity_evening_entertainment     3871 to 4654
19  hotel_amenity_bar_loungehotel_amenity_beachhot...       794 to 833
0                                                 NaN      350 to 1488
1                                                 NaN              NaN
2                                                 NaN              NaN
3                                                 NaN  ₱1,000 - ₱2,000
4                                                 NaN              NaN
5                                                 NaN              NaN
6                                                 NaN    ₱479 - ₱2,396
7                                                 NaN              NaN
8                                                 NaN      190 to 1490
9                                                 NaN              NaN
10                                                NaN       195 to 475
11                                                NaN      ₱240 - ₱479
12                                                NaN              NaN
13                                                NaN       190 to 490
14                                                NaN       275 to 298
15                                                NaN       295 to 988
16                                                NaN    ₱479 - ₱2,875
17                                                NaN              NaN
18                                                NaN              NaN
19                                                NaN      ₱240 - ₱479
4                                                 NaN              NaN
8                                                 NaN              NaN

    NumberofRooms                                          OtherData  \
1           580.0  El Nido in Palawan is most famous for its para...
4           150.0  Take a stroll through history lane within the ...
7           262.0  Undoubtedly one of the most photographed and i...
9           498.0  The Ifugao people were highly skilled in carvi...
10          282.0  Siargao’s rise as a top tourist spot in the Ph...
11          609.0  The gateway to the Philippines’ Last Frontier,...
12          150.0  Included in the UNESCO World Heritage Natural ...
13           36.0  Long hailed as one of the best beaches in the ...
14           58.0  It is a trek to get to the hanging coffins in ...
15          142.0  A tour of Corregidor Island is a must-see for ...
16           61.0  The only thing more exciting than admiring one...
17           50.0  If you are unsure where to snorkel to see some...
18          149.0  You can take a tour of the former Subic Bay Na...
19           46.0  Over the years, the bridge, which was was orig...
0             NaN  CUISINES Italian, Chinese, Japanese, American,...
1             NaN  Takeout, Seating, Parking Available, Validated...
2             NaN                                   Vegetarian Foods
3             NaN                                      Lunch, Dinner
4             NaN                                      Lunch, Dinner
5             NaN                                      Lunch, Dinner
6             NaN                                      Lunch, Dinner
7             NaN                              Dinner, Drinks, Lunch
8             NaN  Vegan Options, Vegetarian Friendly, Gluten Fre...
9             NaN                              Lunch, Dinner, Brunch
10            NaN  Reservations, Private Dining, Seating, Serves ...
11            NaN                                      Vegan Options
12            NaN                                 Vegetarian options
13            NaN                                 Vegetarian options
14            NaN                                 Vegetarian options
15            NaN                                 Vegetarian options
16            NaN                          Dinner, Lunch, Late Night
17            NaN  Takeout, Reservations, Seating, Serves Alcohol...
18            NaN  Takeout, Reservations, Seating, Serves Alcohol...
19            NaN                          Dinner, Lunch, Late Night
4             NaN  Take a stroll through history lane within the ...
8             NaN  Many travelers skip Manila and make their way ...

                                       CustomerReview  \
1   Very good service. Food is good also. Siaomai ...
4   It's a priviledge to be able to stay in this g...
7   When I travelled with my friend in the Philipp...
9   I waited for almost five months to write this ...
10  My gf stayed here when her flight was cancelle...
11  10/10 Experience in Spiral! They definitely ha...
12  In my 5 years living in the Philippines and mo...
13  Overall stay was so perfect that we actually p...
14  thank you and GOD BLESS,I'm very much apprecia...
15  Stayed for 3 nights because I need to do my ch...
16  Super ganda ng ambiance lalo n pag need mo ng ...
17  This hotel has my preference due to the locati...
18  Been here as our flight was cancelled. Crowded...
19  If you are staying in Manila. Stay here!Its lo...
0   Been here a couple of times, and this might be...
1   I am sending this comment to recommend Mr. Dev...
2   Had our dinner business meeting here last week...
3   It is a real good japenese restaurant. Make su...
4   I have tried eating here for lunch on a Sunday...
5   This is your go to place for that good ube (Pu...
6   I love their MOSCATO wine brand from Australia...
7   i enjoyed our breakfast here, so cozy and food...
8   I never get tired of dining at Market Cafe whe...
9   If you like to eat various types of asian cuis...
10  We found this hidden gem while wandering in th...
11  The last time I ate there was in Manila. I was...
12  Very good Great value for money the food looke...
13  You have to accept that the foods from each re...
14  The servers should be taught how to be nice or...
15  Food served are all freshly cooked, well prese...
16  Cosy restaurant, very well located, fine wines...
17  I like their desserts, specially the turon. It...
18  We enjoyed the food in this restaurant. Fresh ...
19  Another top Korean restaurant with non meat op...
4   You can see the Spanish glory in the beautiful...
8   In my own opinion when you say Philippines it'...

                                  Specialty  SeatingCapacity Classification  \
1                                       NaN              NaN            NaN
4                                       NaN              NaN            NaN
7                                       NaN              NaN            NaN
9                                       NaN              NaN            NaN
10                                      NaN              NaN            NaN
11                                      NaN              NaN            NaN
12                                      NaN              NaN            NaN
13                                      NaN              NaN            NaN
14                                      NaN              NaN            NaN
15                                      NaN              NaN            NaN
16                                      NaN              NaN            NaN
17                                      NaN              NaN            NaN
18                                      NaN              NaN            NaN
19                                      NaN              NaN            NaN
0                       Vegetarian Friendly              NaN            NaN
1   Vegetarian Friendly, Gluten Free Option             60.0            NaN
2                            Chinese, Asian            287.0            NaN
3                                  Japanese              NaN            NaN
4                                   Chinese             70.0            NaN
5                                   Chinese             25.0            NaN
6                  Italian, Pizza, European            400.0            NaN
7       Filipino, Bar, Asian, International             70.0            NaN
8             International, Asian, Healthy            270.0            NaN
9                            Chinese, Asian            105.0            NaN
10           Filipino, Asian, International            300.0            NaN
11                                 Filipino            200.0            NaN
12                          Filipino, Asian              NaN            NaN
13                  Chinese, Asian, Seafood            210.0            NaN
14                          Filipino, Asian            300.0            NaN
15                   Filipino, Sushi, Asian              NaN            NaN
16         European, Spanish, Mediterranean             90.0            NaN
17                 Spanish, Filipino, Asian            100.0            NaN
18                  Chinese, Seafood, Asian            200.0            NaN
19                  Korean, Barbecue, Asian             60.0            NaN
4                                       NaN              NaN         Museum
8                                       NaN              NaN           Park

    VisitorsPeryear Entrance Fee
1               NaN          NaN
4               NaN          NaN
7               NaN          NaN
9               NaN          NaN
10              NaN          NaN
11              NaN          NaN
12              NaN          NaN
13              NaN          NaN
14              NaN          NaN
15              NaN          NaN
16              NaN          NaN
17              NaN          NaN
18              NaN          NaN
19              NaN          NaN
0               NaN          NaN
1               NaN          NaN
2               NaN          NaN
3               NaN          NaN
4               NaN          NaN
5               NaN          NaN
6               NaN          NaN
7               NaN          NaN
8               NaN          NaN
9               NaN          NaN
10              NaN          NaN
11              NaN          NaN
12              NaN          NaN
13              NaN          NaN
14              NaN          NaN
15              NaN          NaN
16              NaN          NaN
17              NaN          NaN
18              NaN          NaN
19              NaN          NaN
4         2000000.0           75
8         1800000.0           50

In [17]:
#Let's transfer the data to csv file
import csv

with open('NCR.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
NCR.to_csv("NCR.csv", index = False) #transferring data
NCR = pd.read_csv("NCR.csv")

NCR #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,New World Makati Hotel,Makati,Esperanza,NCR,Fitness Center with Gym / Workout Room,4800 to 5700,580.0,El Nido in Palawan is most famous for its para...,Very good service. Food is good also. Siaomai ...,NaN,NaN,NaN,NaN,NaN
1,Somerset Alabang Manila,Alabang,Filinvest,NCR,Fitness Center with Gym / Workout Room,6991 to 7000,150.0,Take a stroll through history lane within the ...,It's a priviledge to be able to stay in this g...,NaN,NaN,NaN,NaN,NaN
2,Acacia Hotel Manila,Alabang,Filinvest,NCR,Free breakfast Kids stay free Free shuttle or ...,3987 to 4914,262.0,Undoubtedly one of the most photographed and i...,When I travelled with my friend in the Philipp...,NaN,NaN,NaN,NaN,NaN
3,THE PENINSULA MANILA,Makati,Ayala cor Makati,NCR,Banquets & Meetings Business Center,5514 to 5680,498.0,The Ifugao people were highly skilled in carvi...,I waited for almost five months to write this ...,NaN,NaN,NaN,NaN,NaN
4,Bayview Park Hotel Manila,Manila,United Nations,NCR,Free breakfast Children Activities Airport tra...,2275 to 2938,282.0,Siargao’s rise as a top tourist spot in the Ph...,My gf stayed here when her flight was cancelle...,NaN,NaN,NaN,NaN,NaN
5,Sofitel Philippine Plaza Manila,Manila,Roxas Boulevard,NCR,Valet parkingFree High Speed Internet (WiFi) P...,6492 to 7067,609.0,"The gateway to the Philippines’ Last Frontier,...",10/10 Experience in Spiral! They definitely ha...,NaN,NaN,NaN,NaN,NaN
6,Red Planet Manila Bay,Manila,Manila Bay,NCR,Business Center with Internet Access24-hour se...,1800 to 2017,150.0,Included in the UNESCO World Heritage Natural ...,In my 5 years living in the Philippines and mo...,NaN,NaN,NaN,NaN,NaN
7,1775 Adriatico Suites,Manila,Brgy 699,NCR,Free breakfastChildren's television networksHi...,1678 to 2233,36.0,Long hailed as one of the best beaches in the ...,Overall stay was so perfect that we actually p...,NaN,NaN,NaN,NaN,NaN
8,Hotel Kimberly Manila,Manila,Malate,NCR,"Books, DVDs, music for childrenAirport transpo...",2082 to 2162,58.0,It is a trek to get to the hanging coffins in ...,"thank you and GOD BLESS,I'm very much apprecia...",NaN,NaN,NaN,NaN,NaN
9,City Garden Suites,Manila,Ermita,NCR,MicrowaveRefrigeratorFlatscreen TV,1786 to 2394,142.0,A tour of Corregidor Island is a must-see for ...,Stayed for 3 nights because I need to do my ch...,NaN,NaN,NaN,NaN,NaN
10,Regency Grand Suites,Manila,Brich Condo,NCR,Bicycles availableChildren Activities,1710 to 1896,61.0,The only thing more exciting than admiring one...,Super ganda ng ambiance lalo n pag need mo ng ...,NaN,NaN,NaN,NaN,NaN
11,Heroes Hotel,Manila,Florentiono,NCR,Free breakfastEvening entertainmentKids stay free,1360 to 1786,50.0,If you are unsure where to snorkel to see some...,This hotel has my preference due to the locati...,NaN,NaN,NaN,NaN,NaN
12,The Manila Hotel,Manila,Rizal Park,NCR,hotel_amenity_evening_entertainment,3871 to 4654,149.0,You can take a tour of the former Subic Bay Na...,Been here as our flight was cancelled. Crowded...,NaN,NaN,NaN,NaN,NaN
13,Wanderers Guest House,Manila,Nakpil,NCR,hotel_amenity_bar_loungehotel_amenity_beachhot...,794 to 833,46.0,"Over the years, the bridge, which was was orig...",If you are staying in Manila. Stay here!Its lo...,NaN,NaN,NaN,NaN,NaN
14,Cafe Ilang-Ilang,Manila,Rizal Park,NCR,NaN,350 to 1488,NaN,"CUISINES Italian, Chinese, Japanese, American,...","Been here a couple of times, and this might be...",Vegetarian Friendly,NaN,NaN,NaN,NaN
15,Le Bar,Manila,Centro Commercial,NCR,NaN,NaN,NaN,"Takeout, Seating, Parking Available, Validated...",I am sending this comment to recommend Mr. Dev...,"Vegetarian Friendly, Gluten Free Option",60.0,NaN,NaN,NaN
16,Li Li,Manila,Malate,NCR,NaN,NaN,NaN,Vegetarian Foods,Had our dinner business meeting here last week...,"Chinese, Asian",287.0,NaN,NaN,NaN
17,Yurakuen Japanese Restaurant,Manila,Roxas,NCR,NaN,"₱1,000 - ₱2,000",NaN,"Lunch, Dinner",It is a real good japenese restaurant. Make su...,Japanese,NaN,NaN,NaN,NaN
18,Summer Palace,Mandaluyong,Shangrila,NCR,NaN,NaN,NaN,"Lunch, Dinner",I have tried eating here for lunch on a Sunday...,Chinese,70.0,NaN,NaN,NaN
19,Eng Bee Tin,Manila,Binondo,NCR,NaN,NaN,NaN,"Lunch, Dinner",This is your go to place for that good ube (Pu...,Chinese,25.0,NaN,NaN,NaN
20,My Kitchen at the Oasis,Manila,Paco,NCR,NaN,"₱479 - ₱2,396",NaN,"Lunch, Dinner",I love their MOSCATO wine brand from Australia...,"Italian, Pizza, European",400.0,NaN,NaN,NaN
21,Sky Deck at The Bayleaf Hotel,Manila,Intramuros,NCR,NaN,NaN,NaN,"Dinner, Drinks, Lunch","i enjoyed our breakfast here, so cozy and food...","Filipino, Bar, Asian, International",70.0,NaN,NaN,NaN
22,Market Cafe,Manila,brgy 734,NCR,NaN,190 to 1490,NaN,"Vegan Options, Vegetarian Friendly, Gluten Fre...",I never get tired of dining at Market Cafe whe...,"International, Asian, Healthy",270.0,NaN,NaN,NaN
23,Tim Ho Wan,Mandaluyong,Megamall,NCR,NaN,NaN,NaN,"Lunch, Dinner, Brunch",If you like to eat various types of asian cuis...,"Chinese, Asian",105.0,NaN,NaN,NaN
24,Barbara's Heritage Restaurant,Manila,Intramuros,NCR,NaN,195 to 475,NaN,"Reservations, Private Dining, Seating, Serves ...",We found this hidden gem while wandering in th...,"Filipino, Asian, International",300.0,NaN,NaN,NaN
25,The Aristocrat Restaurant,Manila,Roxas,NCR,NaN,₱240 - ₱479,NaN,Vegan Options,The last time I ate there was in Manila. I was...,Filipino,200.0,NaN,NaN,NaN
26,Bistro Remedios,Manila,Malate,NCR,NaN,NaN,NaN,Vegetarian options,Very good Great value for money the food looke...,"Filipino, Asian",NaN,NaN,NaN,NaN
27,Uno Wharf Seafood Palace,Manila,Calvo,NCR,NaN,190 to 490,NaN,Vegetarian options,You have to accept that the foods from each re...,"Chinese, Asian, Seafood",210.0,NaN,NaN,NaN
28,Ristorante Delle Mitre,Manila,Intramuros,NCR,NaN,275 to 298,NaN,Vegetarian options,The servers should be taught how to be nice or...,"Filipino, Asian",300.0,NaN,NaN,NaN
29,Dads-Saisaki-Kamayan,Manila,Ermita,NCR,NaN,295 to 988,NaN,Vegetarian options,"Food served are all freshly cooked, well prese...","Filipino, Sushi, Asian",NaN,NaN,NaN,NaN
30,Casa Armas,Manila,Nakpil,NCR,NaN,"₱479 - ₱2,875",NaN,"Dinner, Lunch, Late Night","Cosy restaurant, very well located, fine wines...","European, Spanish, Mediterranean",90.0,NaN,NaN,NaN
31,Casa Roces,Pasig,San Miguel,NCR,NaN,NaN,NaN,"Takeout, Reservations, Seating, Serves Alcohol...","I like their desserts, specially the turon. It...","Spanish, Filipino, Asian",100.0,NaN,NaN,NaN
32,Tao Yuan Restaurant,Manila,Malate,NCR,NaN,NaN,NaN,"Takeout, Reservations, Seating, Serves Alcohol...",We enjoyed the food in this restaurant. Fresh ...,"Chinese, Seafood, Asian",200.0,NaN,NaN,NaN
33,Korean Palace Restaurant,Manila,Malate,NCR,NaN,₱240 - ₱479,NaN,"Dinner, Lunch, Late Night",Another top Korean restaurant with non meat op...,"Korean, Barbecue, Asian",60.0,NaN,NaN,NaN
34,Intramuros and Fort Santiago,Manila,Intramuros,NCR,NaN,NaN,NaN,Take a stroll through history lane within the ...,You can see the Spanish glory in the beautiful...,NaN,NaN,Museum,2000000.0,75.0
35,Rizal Park,Manila,Ermita,NCR,NaN,NaN,NaN,Many travelers skip Manila and make their way ...,In my own opinion when you say Philippines it'...,NaN,NaN,Park,1800000.0,50.0

In [23]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

Calabarzon = tourism[tourism.Province == 'Calabarzon']
print (Calabarzon)

                       Name      City   Barangay    Province  \
2          Taal Vista Hotel  Tagaytay  Aguinaldo  Calabarzon
3    Tagaytay Wingate Manor  Tagaytay     Maitim  Calabarzon
5   Hotel Kimberly Tagaytay  Tagaytay   Kaybagal  Calabarzon
5     Taal Volcano and Lake  Tagaytay        NaN  Calabarzon
16          Pagsanjan Falls    Laguna        NaN  Calabarzon

                                 Amenities      PriceRange  NumberofRooms  \
2   Fitness Center with Gym / Workout Room    4194 to 6110          261.0
3   Fitness Center with Gym / Workout Room  13333 to 13481           24.0
5   Fitness Center with Gym / Workout Room    3200 to 4420           50.0
5                                      NaN             NaN            NaN
16                                     NaN             NaN            NaN

                                            OtherData  \
2   Tubbataha Reef is regarded as one of the top d...
3   As soon as your flight lands at the airport in...
5   Locals and foreign visitors from Manila often ...
5   Locals and foreign visitors from Manila often ...
16  The only thing more exciting than admiring one...

                                       CustomerReview Specialty  \
2   Awesome hotel. My family and I were here aroun...       NaN
3   Place is a bit far from the highway not to men...       NaN
5   Everything was flawless. Starting from the boo...       NaN
5   Recently exploded but rare to see Volcano in i...       NaN
16  We had such a good morning. Stayed at Casa Del...       NaN

    SeatingCapacity Classification  VisitorsPeryear Entrance Fee
2               NaN            NaN              NaN          NaN
3               NaN            NaN              NaN          NaN
5               NaN            NaN              NaN          NaN
5               NaN           Lake              NaN          NaN
16              NaN          Falls              NaN          270

In [19]:
import csv

with open('Calabarzon.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
Calabarzon.to_csv("Calabarzon.csv", index = False) #transferring data
Calabarzon = pd.read_csv("Calabarzon.csv")

Calabarzon #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,Taal Vista Hotel,Tagaytay,Aguinaldo,Calabarzon,Fitness Center with Gym / Workout Room,4194 to 6110,261.0,Tubbataha Reef is regarded as one of the top d...,Awesome hotel. My family and I were here aroun...,NaN,NaN,NaN,NaN,NaN
1,Tagaytay Wingate Manor,Tagaytay,Maitim,Calabarzon,Fitness Center with Gym / Workout Room,13333 to 13481,24.0,As soon as your flight lands at the airport in...,Place is a bit far from the highway not to men...,NaN,NaN,NaN,NaN,NaN
2,Hotel Kimberly Tagaytay,Tagaytay,Kaybagal,Calabarzon,Fitness Center with Gym / Workout Room,3200 to 4420,50.0,Locals and foreign visitors from Manila often ...,Everything was flawless. Starting from the boo...,NaN,NaN,NaN,NaN,NaN
3,Taal Volcano and Lake,Tagaytay,NaN,Calabarzon,NaN,NaN,NaN,Locals and foreign visitors from Manila often ...,Recently exploded but rare to see Volcano in i...,NaN,NaN,Lake,NaN,NaN
4,Pagsanjan Falls,Laguna,NaN,Calabarzon,NaN,NaN,NaN,The only thing more exciting than admiring one...,We had such a good morning. Stayed at Casa Del...,NaN,NaN,Falls,NaN,270.0

In [22]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

Mindanao = tourism[tourism.Province == 'Mindanao']
print (Mindanao)

            Name   City      Barangay  Province  \
6  DusitD2 Davao  Davao  Stella Hizon  Mindanao

                                           Amenities    PriceRange  \
6  Fitness Center with Gym / Workout RoomBar / lo...  2744 to 4900

   NumberofRooms                                          OtherData  \
6          120.0  If you like jumping into or swimming in cool c...

                                      CustomerReview Specialty  \
6  Beautiful hotel with excellent customer servic...       NaN

   SeatingCapacity Classification  VisitorsPeryear Entrance Fee
6              NaN            NaN              NaN          NaN

In [21]:
import csv

with open('Mindanao.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
Mindanao.to_csv("Mindanao.csv", index = False) #transferring data
Mindanao = pd.read_csv("Mindanao.csv")

Mindanao #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,DusitD2 Davao,Davao,Stella Hizon,Mindanao,Fitness Center with Gym / Workout RoomBar / lo...,2744 to 4900,120.0,If you like jumping into or swimming in cool c...,Beautiful hotel with excellent customer servic...,NaN,NaN,NaN,NaN,NaN

In [26]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

Cebu = tourism[tourism.Province == 'Cebu']
print (Cebu)

                               Name          City      Barangay Province  \
8                    Kandaya Resort  Daanbantayan         Agujo     Cebu
20   Crimson Resort and Spa, Mactan          Cebu     Lapu Lapu     Cebu
21  Jpark Island Resort & Waterpark          Cebu      Maribago     Cebu
22    Movenpick Hotel Mactan Island          Cebu  Punta Engano     Cebu
23           Seda Central Bloc Cebu          Cebu       IT Park     Cebu
24            Lubi Resort Santander          Cebu     Poblacion     Cebu
6                     Kawasan Falls        Badian           NaN     Cebu

                                            Amenities    PriceRange  \
8   Free breakfast Beach Tennis court Children Act...  7904 to 9730
20  Free breakfastBeachCasino and GamblingKids sta...  4151 to 5170
21           Bar / lounge Beach Evening entertainment  4858 to 5659
22  Bar / lounge BeachEvening entertainmentChildre...          5920
23             Fitness Center with Gym / Workout Room          3810
24             Fitness Center with Gym / Workout Room          5438
6                                                 NaN           NaN

    NumberofRooms                                          OtherData  \
8            40.0  Many travelers skip Manila and make their way ...
20          250.0  Mention the best tourist destinations in the P...
21          557.0  Danjugan Island is a rainforest-covered island...
22          245.0  Have you ever fantasized about having your own...
23          214.0  Visitors in Bulusan flock to the Bulusan Volca...
24            6.0  Bonbon Beach in Romblon has fine, white sand, ...
6             NaN  If you like jumping into or swimming in cool c...

                                       CustomerReview Specialty  \
8   We had a wonderful time here. The beachside vi...       NaN
20  We had a unforgettable experience for celebrat...       NaN
21  very nice staff and a good place to catch time...       NaN
22  Great experience! Very friendly and accomodati...       NaN
23  Most of the time I ask for a room service like...       NaN
24  The resort was very hidden, but it also meant ...       NaN
6   Kawasan falls are located in the south of the ...       NaN

    SeatingCapacity Classification  VisitorsPeryear Entrance Fee
8               NaN            NaN              NaN          NaN
20              NaN            NaN              NaN          NaN
21              NaN            NaN              NaN          NaN
22              NaN            NaN              NaN          NaN
23              NaN            NaN              NaN          NaN
24              NaN            NaN              NaN          NaN
6               NaN          Falls              NaN           45

In [27]:
import csv

with open('Cebu.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
Cebu.to_csv("Cebu.csv", index = False) #transferring data
Cebu = pd.read_csv("Cebu.csv")

Cebu #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,Kandaya Resort,Daanbantayan,Agujo,Cebu,Free breakfast Beach Tennis court Children Act...,7904 to 9730,40.0,Many travelers skip Manila and make their way ...,We had a wonderful time here. The beachside vi...,NaN,NaN,NaN,NaN,NaN
1,"Crimson Resort and Spa, Mactan",Cebu,Lapu Lapu,Cebu,Free breakfastBeachCasino and GamblingKids sta...,4151 to 5170,250.0,Mention the best tourist destinations in the P...,We had a unforgettable experience for celebrat...,NaN,NaN,NaN,NaN,NaN
2,Jpark Island Resort & Waterpark,Cebu,Maribago,Cebu,Bar / lounge Beach Evening entertainment,4858 to 5659,557.0,Danjugan Island is a rainforest-covered island...,very nice staff and a good place to catch time...,NaN,NaN,NaN,NaN,NaN
3,Movenpick Hotel Mactan Island,Cebu,Punta Engano,Cebu,Bar / lounge BeachEvening entertainmentChildre...,5920,245.0,Have you ever fantasized about having your own...,Great experience! Very friendly and accomodati...,NaN,NaN,NaN,NaN,NaN
4,Seda Central Bloc Cebu,Cebu,IT Park,Cebu,Fitness Center with Gym / Workout Room,3810,214.0,Visitors in Bulusan flock to the Bulusan Volca...,Most of the time I ask for a room service like...,NaN,NaN,NaN,NaN,NaN
5,Lubi Resort Santander,Cebu,Poblacion,Cebu,Fitness Center with Gym / Workout Room,5438,6.0,"Bonbon Beach in Romblon has fine, white sand, ...","The resort was very hidden, but it also meant ...",NaN,NaN,NaN,NaN,NaN
6,Kawasan Falls,Badian,NaN,Cebu,NaN,NaN,NaN,If you like jumping into or swimming in cool c...,Kawasan falls are located in the south of the ...,NaN,NaN,Falls,NaN,45.0

In [28]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

Baguio = tourism[tourism.Province == 'Baguio']
print (Baguio)

                                               Name    City  \
20                               Mario's Restaurant  Baguio
21                                           Hamada  Baguio
22                                     Mama's Table  Baguio
23                                     Bistro Lokal  Baguio
24  O Dong Tong Samgyeopsal House Korean Restaurant  Baguio

              Barangay Province Amenities        PriceRange  NumberofRooms  \
20  Upper Session Road   Baguio       NaN       310 to 2520            NaN
21        Country Club   Baguio       NaN               NaN            NaN
22            Ambuklao   Baguio       NaN               NaN            NaN
23           Magsaysay   Baguio       NaN       ₱30 - ₱2000            NaN
24           Naguillan   Baguio       NaN  ₱7,188 - ₱23,960            NaN

                                            OtherData  \
20                                Gluten Free Options
21  Takeout, Reservations, Wheelchair Accessible, ...
22               Reservations, Seating, Table Service
23                              Lunch, Dinner, Brunch
24                  Lunch, Dinner, Late Night, Drinks

                                       CustomerReview               Specialty  \
20  Food is still good here as always but has beco...                 Spanish
21  Food was good and priced very well, its not gr...  Japanese, Sushi, Asian
22  We ate here for a birthday celebration. The am...                  Dinner
23  One of the best dining experience in Baguio. F...   Filipino, Cafe, Asian
24  The dynamite kimbap is the best in their menu....           Asian, Korean

    SeatingCapacity Classification  VisitorsPeryear Entrance Fee
20            134.0            NaN              NaN          NaN
21            120.0            NaN              NaN          NaN
22              NaN            NaN              NaN          NaN
23              NaN            NaN              NaN          NaN
24              NaN            NaN              NaN          NaN

In [29]:
import csv

with open('Baguio.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
Baguio.to_csv("Baguio.csv", index = False) #transferring data
Baguio = pd.read_csv("Baguio.csv")

Baguio #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,Mario's Restaurant,Baguio,Upper Session Road,Baguio,NaN,310 to 2520,NaN,Gluten Free Options,Food is still good here as always but has beco...,Spanish,134.0,NaN,NaN,NaN
1,Hamada,Baguio,Country Club,Baguio,NaN,NaN,NaN,"Takeout, Reservations, Wheelchair Accessible, ...","Food was good and priced very well, its not gr...","Japanese, Sushi, Asian",120.0,NaN,NaN,NaN
2,Mama's Table,Baguio,Ambuklao,Baguio,NaN,NaN,NaN,"Reservations, Seating, Table Service",We ate here for a birthday celebration. The am...,Dinner,NaN,NaN,NaN,NaN
3,Bistro Lokal,Baguio,Magsaysay,Baguio,NaN,₱30 - ₱2000,NaN,"Lunch, Dinner, Brunch",One of the best dining experience in Baguio. F...,"Filipino, Cafe, Asian",NaN,NaN,NaN,NaN
4,O Dong Tong Samgyeopsal House Korean Restaurant,Baguio,Naguillan,Baguio,NaN,"₱7,188 - ₱23,960",NaN,"Lunch, Dinner, Late Night, Drinks",The dynamite kimbap is the best in their menu....,"Asian, Korean",NaN,NaN,NaN,NaN

In [30]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

Ilocos = tourism[tourism.Province == 'Ilocos']
print (Ilocos)

              Name   City Barangay Province Amenities PriceRange  \
0  Calle Crisologo  Vigan      NaN   Ilocos       NaN        NaN

   NumberofRooms                                          OtherData  \
0            NaN  The town has successfully managed to preserve ...

                                      CustomerReview Specialty  \
0  Vigan is a capital city of Ilocos Sur. The cit...       NaN

   SeatingCapacity           Classification  VisitorsPeryear Entrance Fee
0              NaN  Old Spanish Style Place         335000.0          NaN

In [31]:
import csv

with open('Ilocos.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
Ilocos.to_csv("Ilocos.csv", index = False) #transferring data
Ilocos = pd.read_csv("Ilocos.csv")

Ilocos #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,Calle Crisologo,Vigan,NaN,Ilocos,NaN,NaN,NaN,The town has successfully managed to preserve ...,Vigan is a capital city of Ilocos Sur. The cit...,NaN,NaN,Old Spanish Style Place,335000.0,NaN

In [32]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

Palawan = tourism[tourism.Province == 'Palawan']
print (Palawan)

                                 Name             City Barangay Province  \
1                        Nacpan Beach          El Nido      NaN  Palawan
2                      Tubbataha Reef     Cagayancillo      NaN  Palawan
7                       Kayangan Lake            Coron      NaN  Palawan
11  Puerto Princesa Underground River  Puerto Princesa      NaN  Palawan
17                       Coral Garden            Coron      NaN  Palawan
20                      Kayangan Lake            Coron      NaN  Palawan

   Amenities PriceRange  NumberofRooms  \
1        NaN        NaN            NaN
2        NaN        NaN            NaN
7        NaN        NaN            NaN
11       NaN        NaN            NaN
17       NaN        NaN            NaN
20       NaN        NaN            NaN

                                            OtherData  \
1   El Nido in Palawan is most famous for its para...
2   Tubbataha Reef is regarded as one of the top d...
7   Undoubtedly one of the most photographed and i...
11  The gateway to the Philippines’ Last Frontier,...
17  If you are unsure where to snorkel to see some...
20  Mention the best tourist destinations in the P...

                                       CustomerReview Specialty  \
1   One of the most beautiful beaches in the Phili...       NaN
2   World class diving with Solitude One.. only mi...       NaN
7   Kayangan Lake a must visit in Coron Palawan! g...       NaN
11  The overall experience was amazing! The underg...       NaN
17  Very pretty, and good for timid swimmers as th...       NaN
20  The lake has crystal clear waters where you ca...       NaN

    SeatingCapacity Classification  VisitorsPeryear Entrance Fee
1               NaN   Beach Resort          36000.0          NaN
2               NaN   Beach Resort          13475.0          NaN
7               NaN           Lake              NaN          300
11              NaN          River        1200000.0          500
17              NaN         Garden         156000.0          200
20              NaN           Lake              NaN          300

In [33]:
import csv

with open('Palawan.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
Palawan.to_csv("Palawan.csv", index = False) #transferring data
Palawan = pd.read_csv("Palawan.csv")

Palawan #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,Nacpan Beach,El Nido,NaN,Palawan,NaN,NaN,NaN,El Nido in Palawan is most famous for its para...,One of the most beautiful beaches in the Phili...,NaN,NaN,Beach Resort,36000.0,NaN
1,Tubbataha Reef,Cagayancillo,NaN,Palawan,NaN,NaN,NaN,Tubbataha Reef is regarded as one of the top d...,World class diving with Solitude One.. only mi...,NaN,NaN,Beach Resort,13475.0,NaN
2,Kayangan Lake,Coron,NaN,Palawan,NaN,NaN,NaN,Undoubtedly one of the most photographed and i...,Kayangan Lake a must visit in Coron Palawan! g...,NaN,NaN,Lake,NaN,300.0
3,Puerto Princesa Underground River,Puerto Princesa,NaN,Palawan,NaN,NaN,NaN,"The gateway to the Philippines’ Last Frontier,...",The overall experience was amazing! The underg...,NaN,NaN,River,1200000.0,500.0
4,Coral Garden,Coron,NaN,Palawan,NaN,NaN,NaN,If you are unsure where to snorkel to see some...,"Very pretty, and good for timid swimmers as th...",NaN,NaN,Garden,156000.0,200.0
5,Kayangan Lake,Coron,NaN,Palawan,NaN,NaN,NaN,Mention the best tourist destinations in the P...,The lake has crystal clear waters where you ca...,NaN,NaN,Lake,NaN,300.0

In [34]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

Legaspi = tourism[tourism.Province == 'Legaspi']
print (Legaspi)

            Name   City Barangay Province Amenities PriceRange  NumberofRooms  \
3  Mayon Volcano  Albay      NaN  Legaspi       NaN        NaN            NaN

                                           OtherData  \
3  As soon as your flight lands at the airport in...

                                      CustomerReview Specialty  \
3  I've been trap in Legazpi city for 2 months be...       NaN

   SeatingCapacity Classification  VisitorsPeryear Entrance Fee
3              NaN        Volcano        1270000.0          NaN

In [35]:
import csv

with open('Legaspi.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
Legaspi.to_csv("Legaspi.csv", index = False) #transferring data
Legaspi = pd.read_csv("Legaspi.csv")

Legaspi #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,Mayon Volcano,Albay,NaN,Legaspi,NaN,NaN,NaN,As soon as your flight lands at the airport in...,I've been trap in Legazpi city for 2 months be...,NaN,NaN,Volcano,1270000.0,NaN

In [36]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

Ifugao = tourism[tourism.Province == 'Ifugao']
print (Ifugao)

                   Name           City Barangay Province Amenities PriceRange  \
9  Banaue Rice Terraces  Nueva Viscaya    Batad   Ifugao       NaN        NaN

   NumberofRooms                                          OtherData  \
9            NaN  The Ifugao people were highly skilled in carvi...

                                      CustomerReview Specialty  \
9  I did several day tours (mostly hikes) ranging...       NaN

   SeatingCapacity Classification  VisitorsPeryear Entrance Fee
9              NaN  Rice Terraces              NaN          NaN

In [37]:
import csv

with open('Ifugao.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
Ifugao.to_csv("Ifugao.csv", index = False) #transferring data
Ifugao = pd.read_csv("Ifugao.csv")

Ifugao #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,Banaue Rice Terraces,Nueva Viscaya,Batad,Ifugao,NaN,NaN,NaN,The Ifugao people were highly skilled in carvi...,I did several day tours (mostly hikes) ranging...,NaN,NaN,Rice Terraces,NaN,NaN

In [38]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

Siargao = tourism[tourism.Province == 'Siargao']
print (Siargao)

       Name          City Barangay Province Amenities PriceRange  \
10  Cloud 9  General Luna      NaN  Siargao       NaN        NaN

    NumberofRooms                                          OtherData  \
10            NaN  Siargao’s rise as a top tourist spot in the Ph...

                                       CustomerReview Specialty  \
10  Price of admission is very low, but it's time ...       NaN

    SeatingCapacity Classification  VisitorsPeryear Entrance Fee
10              NaN        Surfing              NaN         None

In [39]:
import csv

with open('Siargao.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
Siargao.to_csv("Siargao.csv", index = False) #transferring data
Siargao = pd.read_csv("Siargao.csv")

Siargao #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,Cloud 9,General Luna,NaN,Siargao,NaN,NaN,NaN,Siargao’s rise as a top tourist spot in the Ph...,"Price of admission is very low, but it's time ...",NaN,NaN,Surfing,NaN,None

In [40]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

Bohol = tourism[tourism.Province == 'Bohol']
print (Bohol)

               Name        City Barangay Province Amenities PriceRange  \
12  Chocolate Hills      Batuan      NaN    Bohol       NaN        NaN
19   Hanging Bridge  Tagbilaran      NaN    Bohol       NaN        NaN

    NumberofRooms                                          OtherData  \
12            NaN  Included in the UNESCO World Heritage Natural ...
19            NaN  Over the years, the bridge, which was was orig...

                                       CustomerReview Specialty  \
12  We have already seen the chocolate hills while...       NaN
19  We absolutely loved this site, it was a great ...       NaN

    SeatingCapacity Classification  VisitorsPeryear Entrance Fee
12              NaN          Hills        2000000.0           50
19              NaN         Bridge              NaN           80

In [41]:
import csv

with open('Bohol.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
Bohol.to_csv("Bohol.csv", index = False) #transferring data
Bohol = pd.read_csv("Bohol.csv")

Bohol #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,Chocolate Hills,Batuan,NaN,Bohol,NaN,NaN,NaN,Included in the UNESCO World Heritage Natural ...,We have already seen the chocolate hills while...,NaN,NaN,Hills,2000000.0,50
1,Hanging Bridge,Tagbilaran,NaN,Bohol,NaN,NaN,NaN,"Over the years, the bridge, which was was orig...","We absolutely loved this site, it was a great ...",NaN,NaN,Bridge,NaN,80

In [42]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

Boracay = tourism[tourism.Province == 'Boracay']
print (Boracay)

           Name   City Barangay Province Amenities PriceRange  NumberofRooms  \
13  White Beach  Aklan      NaN  Boracay       NaN        NaN            NaN

                                            OtherData  \
13  Long hailed as one of the best beaches in the ...

                                       CustomerReview Specialty  \
13  White beach is the most popular beach in Borac...       NaN

    SeatingCapacity Classification  VisitorsPeryear Entrance Fee
13              NaN   Beach Resort        2000000.0          NaN

In [43]:
import csv

with open('Boracay.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
Boracay.to_csv("Boracay.csv", index = False) #transferring data
Boracay = pd.read_csv("Boracay.csv")

Boracay #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,White Beach,Aklan,NaN,Boracay,NaN,NaN,NaN,Long hailed as one of the best beaches in the ...,White beach is the most popular beach in Borac...,NaN,NaN,Beach Resort,2000000.0,NaN

In [44]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

MountainProvince = tourism[tourism.Province == 'Mountain Province']
print (MountainProvince)

               Name    City     Barangay           Province Amenities  \
14  Hanging Coffins  Sagada  Echo Valley  Mountain Province       NaN

   PriceRange  NumberofRooms  \
14        NaN            NaN

                                            OtherData  \
14  It is a trek to get to the hanging coffins in ...

                                       CustomerReview Specialty  \
14  I've been to this place and going there you'll...       NaN

    SeatingCapacity Classification  VisitorsPeryear Entrance Fee
14              NaN            NaN              NaN          300

In [45]:
import csv

with open('MountainProvince.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
MountainProvince.to_csv("MountainProvince.csv", index = False) #transferring data
MountainProvince = pd.read_csv("MountainProvince.csv")

MountainProvince #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,Hanging Coffins,Sagada,Echo Valley,Mountain Province,NaN,NaN,NaN,It is a trek to get to the hanging coffins in ...,I've been to this place and going there you'll...,NaN,NaN,NaN,NaN,300

In [46]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

Cavite = tourism[tourism.Province == 'Cavite']
print (Cavite)

                 Name               City Barangay Province Amenities  \
15  Corregidor Island  Corregidor Island      NaN   Cavite       NaN

   PriceRange  NumberofRooms  \
15        NaN            NaN

                                            OtherData  \
15  A tour of Corregidor Island is a must-see for ...

                                       CustomerReview Specialty  \
15  The scenery was just beyond words the first ti...       NaN

    SeatingCapacity Classification  VisitorsPeryear Entrance Fee
15              NaN         Island              NaN          200

In [47]:
import csv

with open('Cavite.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
Cavite.to_csv("Cavite.csv", index = False) #transferring data
Cavite = pd.read_csv("Cavite.csv")

Cavite #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,Corregidor Island,Corregidor Island,NaN,Cavite,NaN,NaN,NaN,A tour of Corregidor Island is a must-see for ...,The scenery was just beyond words the first ti...,NaN,NaN,Island,NaN,200

In [48]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

Bataan = tourism[tourism.Province == 'Bataan']
print (Bataan)

               Name   City  Barangay Province Amenities PriceRange  \
18  Jungle Training  Subic  Freeport   Bataan       NaN        NaN

    NumberofRooms                                          OtherData  \
18            NaN  You can take a tour of the former Subic Bay Na...

                                       CustomerReview Specialty  \
18  I tried to contact this company several times ...       NaN

    SeatingCapacity Classification  VisitorsPeryear Entrance Fee
18              NaN         Jungle              NaN          NaN

In [49]:
import csv

with open('Bataan.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
Bataan.to_csv("Bataan.csv", index = False) #transferring data
Bataan = pd.read_csv("Bataan.csv")

Bataan #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,Jungle Training,Subic,Freeport,Bataan,NaN,NaN,NaN,You can take a tour of the former Subic Bay Na...,I tried to contact this company several times ...,NaN,NaN,Jungle,NaN,NaN

In [50]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

NegrosOccidental = tourism[tourism.Province == 'Negros Occidental']
print (NegrosOccidental)

               Name     City Barangay           Province Amenities PriceRange  \
21  Danjugan Island  Cauayan      NaN  Negros Occidental       NaN        NaN

    NumberofRooms                                          OtherData  \
21            NaN  Danjugan Island is a rainforest-covered island...

                                       CustomerReview Specialty  \
21  Danjugan Island is for me one of the best plac...       NaN

    SeatingCapacity Classification  VisitorsPeryear Entrance Fee
21              NaN   Beach Resort              NaN         2950

In [51]:
import csv

with open('NegrosOccidental.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
NegrosOccidental.to_csv("NegrosOccidental.csv", index = False) #transferring data
NegrosOccidental = pd.read_csv("NegrosOccidental.csv")

NegrosOccidental #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,Danjugan Island,Cauayan,NaN,Negros Occidental,NaN,NaN,NaN,Danjugan Island is a rainforest-covered island...,Danjugan Island is for me one of the best plac...,NaN,NaN,Beach Resort,NaN,2950

In [52]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

Laguna = tourism[tourism.Province == 'Laguna']
print (Laguna)

              Name     City Barangay Province Amenities PriceRange  \
22  Sundang Island  Cavinti      NaN   Laguna       NaN        NaN

    NumberofRooms                                          OtherData  \
22            NaN  Have you ever fantasized about having your own...

                                       CustomerReview Specialty  \
22  Beautiful home. For me, not a place you wanna ...       NaN

    SeatingCapacity Classification  VisitorsPeryear Entrance Fee
22              NaN           Lake              NaN         3400

In [53]:
import csv

with open('Laguna.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
Laguna.to_csv("Laguna.csv", index = False) #transferring data
Laguna = pd.read_csv("Laguna.csv")

Laguna #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,Sundang Island,Cavinti,NaN,Laguna,NaN,NaN,NaN,Have you ever fantasized about having your own...,"Beautiful home. For me, not a place you wanna ...",NaN,NaN,Lake,NaN,3400

In [54]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

Sorsogon = tourism[tourism.Province == 'Sorsogon']
print (Sorsogon)

             Name     City Barangay  Province Amenities PriceRange  \
23  Bayugin Falls  Bulusan      NaN  Sorsogon       NaN        NaN

    NumberofRooms                                          OtherData  \
23            NaN  Visitors in Bulusan flock to the Bulusan Volca...

                                       CustomerReview Specialty  \
23  The waterfall is hard to reach. We had to park...       NaN

    SeatingCapacity Classification  VisitorsPeryear Entrance Fee
23              NaN          Falls              NaN           15

In [55]:
import csv

with open('Sorsogon.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
Sorsogon.to_csv("Sorsogon.csv", index = False) #transferring data
Sorsogon = pd.read_csv("Laguna.csv")

Sorsogon #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,Sundang Island,Cavinti,NaN,Laguna,NaN,NaN,NaN,Have you ever fantasized about having your own...,"Beautiful home. For me, not a place you wanna ...",NaN,NaN,Lake,NaN,3400

In [56]:
# Now we that we have unique names from the province column, we will now create a csv file for each Location

#['Busuanga Island', 'NCR', 'Calabarzon', 'Mindanao', 'Cebu',
#       'Baguio', 'Ilocos', 'Palawan', 'Legaspi', 'Ifugao', 'Siargao',
#       'Bohol', 'Boracay', 'Mountain Province', 'Cavite', 'Bataan',
#       'Negros Occidental', 'Laguna', 'Sorsogon', 'Romblon'], dtype=object)

#Busuanga Island

Romblon = tourism[tourism.Province == 'Romblon']
print (Romblon)

            Name     City Barangay Province Amenities PriceRange  \
24  Bonbon Beach  Romblon      NaN  Romblon       NaN        NaN

    NumberofRooms                                          OtherData  \
24            NaN  Bonbon Beach in Romblon has fine, white sand, ...

                                       CustomerReview Specialty  \
24  Beach by itself is very nice, but old woman, G...       NaN

    SeatingCapacity Classification  VisitorsPeryear Entrance Fee
24              NaN   Beach Resort              NaN         None

In [57]:
import csv

with open('Romblon.csv', 'wb') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    
Romblon.to_csv("Romblon.csv", index = False) #transferring data
Romblon = pd.read_csv("Romblon.csv")

Romblon #print to check if files are written

#you can check out the files in your drive

,Name,City,Barangay,Province,Amenities,PriceRange,NumberofRooms,OtherData,CustomerReview,Specialty,SeatingCapacity,Classification,VisitorsPeryear,Entrance Fee
0,Bonbon Beach,Romblon,NaN,Romblon,NaN,NaN,NaN,"Bonbon Beach in Romblon has fine, white sand, ...","Beach by itself is very nice, but old woman, G...",NaN,NaN,Beach Resort,NaN,None