In [1]:
!pip install pandas
import pandas as pd
import numpy as np
!pip install openpyxl

Requirement already satisfied: pandas in /srv/conda/envs/notebook/lib/python3.7/site-packages (1.2.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas) (2021.1)
Requirement already satisfied: numpy>=1.16.5 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas) (1.20.2)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: openpyxl in /srv/conda/envs/notebook/lib/python3.7/site-packages (3.0.7)
Requirement already satisfied: et-xmlfile in /srv/conda/envs/notebook/lib/python3.7/site-packages (from openpyxl) (1.1.0)

In [2]:
#Part 1: Using data found in sales.csv. Perform the following task:
# 1. Standardize the Price column
# 2. Identify and remove outliers in the dataset. 


sales = pd.read_csv('sales.csv')

#Standardiztion of Price
sales.insert(3, "standardized_nw", 0)
sales.Price = sales.Price.replace('[,]', '', regex=True).astype(float) 
sales.standardized_nw = (sales.Price-np.mean(sales.Price))/(np.std(sales.Price))

#Identification and removal of the outliers using Six Sigma
n = np.mean(sales.Price)
s = np.std(sales.Price)
ll = max (0, n-3*s)
ul = n + 3*s
sales_cleaned1 = sales[sales.Price>= ll]
sales_cleaned2 = sales_cleaned1[sales.Price <= ul]
sales_cleaned2

#saving to csv
sales_cleaned2.to_csv("Pareja_sales.csv", index = False)
Pareja_sales = pd.read_csv("Pareja_sales.csv")
Pareja_sales

/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:19: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

,Transaction_date,Product,Price,standardized_nw,Payment_Type,Name,City,State,Country,Account_Created,Last_Login,Latitude,Longitude
0,1/2/2009 6:17,Product1,1200.0,-0.372712,Mastercard,carolina,Basildon,England,United Kingdom,1/2/2009 6:00,1/2/2009 6:08,51.500000,-1.116667
1,1/2/2009 4:53,Product1,1200.0,-0.372712,Visa,Betina,Parkville,MO,United States,1/2/2009 4:42,1/2/2009 7:49,39.195000,-94.681940
2,1/2/2009 13:08,Product1,1200.0,-0.372712,Mastercard,Federica e Andrea,Astoria,OR,United States,1/1/2009 16:21,1/3/2009 12:32,46.188060,-123.830000
3,1/3/2009 14:44,Product1,1200.0,-0.372712,Visa,Gouya,Echuca,Victoria,Australia,9/25/2005 21:13,1/3/2009 14:22,-36.133333,144.750000
4,1/4/2009 12:56,Product2,3600.0,1.610806,Visa,Gerd W,Cahaba Heights,AL,United States,11/15/2008 15:47,1/4/2009 12:45,33.520560,-86.802500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,1/20/2009 10:42,Product2,3600.0,1.610806,Diners,esther,Huddersfield,NaN,United Kingdom,1/20/2009 9:15,3/1/2009 3:29,53.650000,-1.783333
977,1/22/2009 14:25,Product1,1200.0,-0.372712,Visa,Hans-Joerg,Belfast,Northern Ireland,United Kingdom,11/10/2008 12:15,3/1/2009 3:37,54.583333,-5.933333
978,1/28/2009 5:36,Product2,3600.0,1.610806,Visa,Christiane,Black River,Black River,Mauritius,1/9/2009 8:10,3/1/2009 4:40,-20.360278,57.366111
979,1/8/2009 11:55,Product1,1200.0,-0.372712,Diners,julie,Haverhill,England,United Kingdom,11/29/2006 13:31,3/1/2009 7:28,52.083333,0.433333
980,1/12/2009 21:30,Product1,1200.0,-0.372712,Visa,Julia,Madison,WI,United States,11/17/2008 22:24,3/1/2009 10:14,43.073060,-89.401110

In [3]:
# Part 2: Using the data in Handling Missing Values.csv
# 1. Handle all the missing values. Provide and exlanation for choosing specific method 
#   (delete, impute or keep; if impute, why mean, median or mode?) in handling specific missing values

data = pd.read_csv('Handling_Missing_Values.csv')

#remove data with 2 or more missing values
data1 = data.dropna(thresh = 6)

#filling the sex data with the mode
mode_value=data1['Sex'].mode()
data1['Sex']=data1['Sex'].fillna(mode_value[0])


# using data1.skew(axis = 0, skipna = True) the data is moderately skwed
# use of median to fill the data for income and number of children. 
data1

median_value=data1['Income'].median()
data1['Income']=data1['Income'].fillna(median_value)
data1

median_value1=data1['Children'].median()
data1['Children']=data1['Children'].fillna(median_value1)


#saving to csv
data1.to_csv("Pareja_Handling_Missing_Values.csv", index = False)
Pareja_Handling_Missing_Values = pd.read_csv("Pareja_Handling_Missing_Values.csv")
Pareja_Handling_Missing_Values

/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

    ID     Sex  Age   Income Employed  Children Buy_Car
0    1    Male   25  25146.0   Single       0.0      No
1    2    Male   30  26939.0  Married       2.0     Yes
2    3    Male   27  26693.0  Married       0.0      No
3    4    Male   28  26666.0  Married       3.0     Yes
4    5    Male   29  25899.0  Married       0.0      No
5    6    Male   28  26462.0  Married       1.0      No
6    7  Female   28  26234.0  Married       3.0     Yes
7    8    Male   30  26037.0  Married       2.0     Yes
8    9  Female   28  26167.0  Married       1.0     Yes
9   11  Female   28  26905.0   Single       0.0      No
10  12    Male   30  26195.0   Single       1.0     Yes
11  13  Female   30  26514.0  Married       4.0     Yes
12  14  Female   28  26969.0  Married       4.0     Yes
13  15    Male   28  26234.0  Married       0.0      No
14  16    Male   27  26229.0  Married       0.0      No
15  17  Female   26  25094.0  Married       0.0      No
16  19    Male   28  26601.0  Married       1.0      No
17  20    Male   29  25427.0  Married       1.0      No

In [4]:
# Part 3: Application
# 1. Gather Data From Any Source (it would be better if you use your own dta)
# 2. Preprocess the data you gathered.

data = pd.read_excel('Survey.xlsx')
data = data.iloc[0:35,0:12] #remove the empty columns
data = data.dropna(thresh = 10) #use data.shape to check how many rows are omitted

# use data.isnull().sum() to check the column with missing data
# mode is used for categorical data and median is used for numerical data
a = ['Place of Residence', 'Work Background of the Shopper', 'Mode of Transportation', 
     'Frequency of Shopping','Time of Shopping', 'Source of Everyday Food','Day of Shopping',
     'Age of the Person who do the Shopping' ]
for i in a:
    mode_value=data[i].mode()
    data[i]=data[i].fillna(mode_value[0])

b = ['Size of Household','Time Travel (One Way in Minutes)', 
     'Shopping Time (inc the time in queuing in hours)']
for i in b:
    median_value=data[i].median()
    data[i]=data[i].fillna(median_value)

#Identification and removal of the outliers using Six Sigma
#data.describe(include="all") to check the standard deviation
for i in b:
    n = np.mean(data[i])
    s = np.std(data[i])
    ll = max (0, n-3*s)
    ul = n + 3*s
    data = data[data[i]>= ll]
    data = data[data[i] <= ul]

#saving to csv
data.to_csv("Pareja_Survey.csv", index = False)
Pareja_Survey = pd.read_csv("Pareja_Survey.csv")
Pareja_Survey

,ID,Place of Residence,Size of Household,Age of the Person who do the Shopping,Work Background of the Shopper,Source of Everyday Food,Mode of Transportation,Time Travel (One Way in Minutes),Shopping Time (inc the time in queuing in hours),Frequency of Shopping,Day of Shopping,Time of Shopping
0,1,ParaÃ±aque,6.0,31 - 40,Unemployed,Wet Market,Walking,5.0,2.00,Every 7 days,Saturday,7:01 AM - 9:00 AM
1,2,Outside Metro Manila,5.0,51 - 60,Working but No Work from Home at the Moment,Grocery,"Private Vehicle (Cars, Private Tricycle, Motor...",10.0,2.00,Every 7 days,Tuesday,1:01 PM - 3:00 PM
2,3,Outside Metro Manila,6.0,51 - 60,Working but No Work from Home at the Moment,Grocery,"Private Vehicle (Cars, Private Tricycle, Motor...",10.0,4.00,Every 7 days,Friday,1:01 PM - 3:00 PM
3,4,Outside Metro Manila,15.0,51 - 60,Essential Workforce,Wet Market,"Private Vehicle (Cars, Private Tricycle, Motor...",15.0,2.00,Everyday,Monday,7:01 AM - 9:00 AM
4,6,Manila,2.0,21- 30,Working but No Work from Home at the Moment,Wet Market,Walking,5.0,5.00,Every 4 days,Wednesday,11:01 AM - 1:00 PM
5,7,Caloocan,4.0,21- 30,Working but No Work from Home at the Moment,Grocery,"Private Vehicle (Cars, Private Tricycle, Motor...",30.0,1.17,Every 6 days,Wednesday,11:01 AM - 1:00 PM
6,8,Outside Metro Manila,7.0,41 - 50,Unemployed,Grocery,"Private Vehicle (Cars, Private Tricycle, Motor...",10.0,2.00,Every 7 days,Wednesday,7:01 AM - 9:00 AM
7,9,Outside Metro Manila,2.0,60 and above,Unemployed,Wet Market,Walking,30.0,2.50,Every 7 days,Monday,7:01 AM - 9:00 AM
8,15,Las PiÃ±as,3.0,41 - 50,Unemployed,Grocery,"Private Vehicle (Cars, Private Tricycle, Motor...",10.0,5.00,Every 7 days,Friday,1:01 PM - 3:00 PM
9,16,Quezon City,5.0,60 and above,Unemployed,Grocery,Walking,15.0,4.00,Every 7 days,Thursday,7:01 AM - 9:00 AM
10,17,Quezon City,5.0,51 - 60,Working but No Work from Home at the Moment,Wet Market,Walking,30.0,1.50,Every 7 days,Wednesday,Before 7:00 AM
11,18,Mandaluyong,2.0,41 - 50,Unemployed,Grocery,"Private Vehicle (Cars, Private Tricycle, Motor...",20.0,2.50,Every 7 days,Thursday,11:01 AM - 1:00 PM
12,19,Caloocan,4.0,21- 30,Working but No Work from Home at the Moment,Grocery,"Private Vehicle (Cars, Private Tricycle, Motor...",10.0,4.00,Every 7 days,Thursday,1:01 PM - 3:00 PM
13,20,Outside Metro Manila,3.0,21- 30,Essential Workforce,Grocery,"Private Vehicle (Cars, Private Tricycle, Motor...",10.0,1.00,Every 7 days,Friday,3:01 PM - 5:00 PM
14,21,Manila,4.0,21- 30,Work from Home,Grocery,Walking,5.0,1.00,Every 7 days,Thursday,11:01 AM - 1:00 PM
15,22,Outside Metro Manila,4.0,21- 30,Essential Workforce,Grocery,Walking,10.0,1.00,Every 7 days,Sunday,1:01 PM - 3:00 PM
16,23,Caloocan,3.0,60 and above,Unemployed,Grocery,"Private Vehicle (Cars, Private Tricycle, Motor...",10.0,3.00,Every 7 days,Thursday,1:01 PM - 3:00 PM
17,24,Outside Metro Manila,5.0,51 - 60,Unemployed,Wet Market,Walking,30.0,3.00,Every 7 days,Wednesday,Before 7:00 AM
18,25,Mandaluyong,3.0,31 - 40,Work from Home,Grocery,Private Vehicle,30.0,60.00,Every 6 days,Wednesday,11:01 AM - 1:00 PM
19,27,Marikina,3.0,20 and below,Unemployed,Wet Market,Motorcycle,30.0,2.50,Every 7 days,Thursday,7:01 AM - 9:00 AM
20,28,Paranaque,6.0,61 and above,Unemployed,Online Shopping,"Private Vehicle (Cars, Private Tricycle, Motor...",0.0,0.00,Every 7 days,Sunday,7:01 AM - 9:00 AM
21,30,Outside Metro Manila,5.0,51 - 60,Work from Home,Wet Market,Motorcycle,5.0,3.00,Every 7 days,Monday,7:01 AM - 9:00 AM
22,31,Outside Metro Manila,3.0,31 - 40,Working but No Work from Home at the Moment,Grocery,Owned PUV,10.0,5.00,Every 7 days,Thursday,9:01 AM - 11:00 AM
23,32,San Juan,3.0,51 - 60,Unemployed,Grocery,Owned PUV,20.0,4.50,Every 7 days,Sunday,9:01 AM - 11:00 AM
24,33,Pasig,5.0,21 - 30,Work from Home,Wet Market,Private Vehicle,15.0,60.00,Every 7 days,Friday,7:01 AM - 9:00 AM
25,34,Manila,4.0,41 - 50,Essential Workforce,Online Shopping,"Private Vehicle (Cars, Private Tricycle, Motor...",0.0,0.00,Every 7 days,Thursday,7:01 AM - 9:00 AM
26,35,Taguig,3.0,31 - 40,Unemployed,Online Shopping,"Private Vehicle (Cars, Private Tricycle, Motor...",0.0,0.00,Every 7 days,Thursday,7:01 AM - 9:00 AM